[tool.poetry]
name = "24_trancate_func"
version = "0.1.0"
description = "Exercise"
authors = ["vovs03"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "3.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
